"""Initial migration

Revision ID: c16e3fc4fdeb
Revises: 
Create Date: 2024-06-07 17:07:34.623337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16e3fc4fdeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('notary_actions', schema=None) as batch_op:
        batch_op.alter_column('id_action',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_notary_actions_category_id', 'categories', ['category_id'], ['id_category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notary_actions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notary_actions_category_id', type_='foreignkey')
        batch_op.alter_column('id_action',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('id_category',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
